### ISSUE TITLE
想确认一下，这里的`CREATE_REGISTER_KEY`是不是没有用上？

### ISSUE THREAD

**Issue by freewind** [Bytom/dashboard#28]
在阅读源代码的过程中，我发现有一个action的type为`CREATE_REGISTER_KEY`，在代码库中只出现了这么一次，所以想确认一下，它是不是没有用上？

https://github.com/Bytom/dashboard/blob/5d950cb7ca6b1109812ca89e2e8b7641a10d96bd/src/features/core/actions.js#L64

因为我对react/redux还不是非常熟练，不太确定是不是我理解错了。感谢

**Comment by ZhitingLin** [comment]
确实是没有用到，之前是为了redux的state比较好了解是否成功create了key。

**Comment by freewind** [comment]
@ZhitingLin 谢谢这么快的回复

**Comment by freewind** [comment]
是否需要我提交一个PR把它删除？可以防止对其它的阅读者产生影响

**Comment by ZhitingLin** [comment]
欢迎你提交pr，我们现在前端还是有些代码还不完善。
