### ISSUE TITLE
[外部测试] Dashboard显示交易的分页页面，实际上拿的是全部的transaction

### ISSUE THREAD

**Issue by freewind** [Bytom/dashboard#35]
下面这个页面是有分页的，我猜它只会取当前页的数据（几十条左右）：
![image](https://user-images.githubusercontent.com/333781/40176238-4c5b17b8-5a0d-11e8-8ae3-82f83f0d7951.png)

但是实际上通过Chrome的开发工具，发现它取回的数据非常多，应该有几千上万条，这里贴不下来。访问的路径是`/list-transactions`，body是`{"detail":true}`，没有跟分页相关的参数

**Comment by wliyongfeng** [comment]
目前后端没有做分页，后续会完善。

**Comment by freewind** [comment]
好的，加油
